### ISSUE TITLE
Cannot see any smoke

### ISSUE THREAD

**Issue by DomDumont** [CBerry22/Reactive-Smoke-in-Godot-4#1]
Hi, on my pc I cannot see any smoke at all, even if the code break into _
**on_explode_timer_timeout**

everything seems ok when i step over :

```
var smoke = smoke_volume.instantiate()
get_parent().add_child(smoke)
smoke.global_position = global_position
queue_free()
```

Maybe a material issue ?

I am using 4.0.2 Godot stable with an nvidia 3070

Thanks

**Comment by CoreAidan** [comment]
seems like this is caused to Godot 4.0.2.stable resetting the default environment value to blank. under project settings -> rendering -> environment -> defaults -> default environment set the value to the one found in the root of the project labeled "default_environment.tres" that should fix your issue

**Comment by DomDumont** [comment]
Thanks a lot. Will try asap.
